//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaParilowApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<System.DateTime> FilingDate { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<int> Executor_ID { get; set; }
        public Nullable<int> Complaint_ID { get; set; }
    
        public virtual Complaints Complaints { get; set; }
        public virtual Executors Executors { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual TypsApplications TypsApplications { get; set; }
    }
}
