//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaParilowApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumbers { get; set; }
        public string Email { get; set; }
        public Nullable<int> AdressName_ID { get; set; }
        public Nullable<int> AdressNumber { get; set; }
        public Nullable<int> ApartmentNumber { get; set; }
        public Nullable<int> Users_ID { get; set; }
    
        public virtual Adresses Adresses { get; set; }
        public virtual Users Users { get; set; }
        public virtual Complaints Complaints { get; set; }
    }
}
