//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaParilowApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppDataBaseEntities : DbContext
    {
        public ppDataBaseEntities()
            : base("name=ppDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static ppDataBaseEntities _context;
        public static ppDataBaseEntities GetContext()
        {
            if (_context == null)
                _context = new ppDataBaseEntities();
            return _context;
        }
        public virtual DbSet<Adresses> Adresses { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<Executors> Executors { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypsApplications> TypsApplications { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
